map:
  image: floor_plan_dxf.png
  resolution: 0.02
  origin:
  - -3.3530502999999996
  - -13.582111300000001
  - 0.0
  occupied_thresh: 0.65
  free_thresh: 0.196
  negate: 0
dimensions:
  width_meters: 6.661100599999999
  height_meters: 25.719222600000002
  width_pixels: 333
  height_pixels: 1285
pathfinding:
  algorithm: A*
  allow_diagonal: true
  heuristic: euclidean
  obstacle_threshold: 128
  safety_margin_cm: 10
coordinate_system:
  unit: meters
  origin_description: Bottom-left corner of the map
  x_axis: East
  y_axis: North
source:
  format: DXF
  original_file: floor_plan.dxf
