name: e57_nav
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pdal>=2.5
  - python-pdal>=3.2
  - numpy>=1.21
  - pip
  - pip:
    - open3d>=0.17.0
    - Pillow>=9.0.0
    - PyYAML>=6.0
    - scipy>=1.7.0